apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app-container
        # This image name will be replaced by the GitHub Action
        image: gcr.io/[PROJECT_ID]/[AR_REPO_NAME]/python-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: python-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

